### ISSUE TITLE
Error on first Tab

### ISSUE THREAD

**Issue by jasperlepardo** [openam/bootstrap-responsive-tabs#48] opened 2015-11-23 12:44 UTC
I have 4 tabs. When toggling on 2nd to 4th tab, other tabs are collapsing, but when I toggle on the 1st tab while either of the 2nd, 3rd or 4th tab are open, the other is not closing.

**Comment by cbier** [comment] 2015-12-13 05:58
+1

**Comment by openam** [comment] 2016-01-02 22:35
Closing as it's a duplicate of #45.

**Closed by openam** 2016-01-02 22:35 UTC
